version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - savoiringfaire
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: pin-project
    versions:
    - 0.4.27
