version: "3.8"
services:
  redis:
    image: redis
  web:
    build: .
    environment:
      - REDIS_CONNECTION_STRING=redis://redis
      - LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - "8081:8081"